#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

fail=false
pippath="" # The pip path
missing="" # Which packages are missing
RED='\033[0;31m'
NOCOLOR='\033[0m'
BOLD='\033[1m'
NOBOLD='\033[0m'

if command -v pip >/dev/null; then
    pippath="pip"
elif command -v pip3 >/dev/null; then
    pippath="pip3"
else
    printf "${RED}Unable to find ${BOLD}pip${NOBOLD}${RED} or ${BOLD}pip3${NOBOLD}${RED}, have you remembered to activate your virtual environment?\n${NOCOLOR}"
    exit 1
fi

if ! $pippath --disable-pip-version-check list | grep -E 'black' >/dev/null; then
    missing="${missing} ${BOLD}black${NOBOLD}${RED},"
    fail=true
fi

if ! $pippath  --disable-pip-version-check list | grep -E 'flake8' >/dev/null; then 
    missing="${missing} ${BOLD}flake8${NOBOLD}${RED},"
    fail=true
fi

if [ $fail = true ]; then
    printf "${RED}Unable to find${missing} have you remembered to activate your virtual environment?\n${NOCOLOR}"
    exit 1
fi

cd frontend
npx lint-staged
