version: "3"

services:
  backend:
    container_name: backend
    build:
      context: backend/
      dockerfile: Dockerfile
      args:
        DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME}"
        DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
        DJANGO_SUPERUSER_EMAIL: "${DJANGO_SUPERUSER_EMAIL}"
    environment:
      - GROUPID=${GROUPID}
    networks:
      backend_bridge:
        ipv4_address: 10.${GROUPID}.0.4

  frontend:
    container_name: frontend
    build:
      context: frontend/
      dockerfile: Dockerfile
      args:
        GROUPID: ${GROUPID}
        DOMAIN: ${DOMAIN}
        URL_PREFIX: ${URL_PREFIX}
        PORT_PREFIX: ${PORT_PREFIX}
    networks:
      backend_bridge:
        ipv4_address: 10.${GROUPID}.0.5

  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      - GROUPID=${GROUPID}
      - PORT_PREFIX=${PORT_PREFIX}
    networks:
      backend_bridge:
        ipv4_address: 10.${GROUPID}.0.6

networks:
  backend_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 10.${GROUPID}.0.0/18
