version: "3"

services:
  backend:
    container_name: backend
    build:
      context: backend/
      dockerfile: Dockerfile
      args:
        DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME}"
        DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
        DJANGO_SUPERUSER_EMAIL: "${DJANGO_SUPERUSER_EMAIL}"
    networks:
      backend_bridge:
        ipv4_address: 10.0.0.4

  frontend:
    container_name: frontend
    build:
      context: frontend/
      dockerfile: Dockerfile
      args:
        DOMAIN: ${DOMAIN}
        URL_PREFIX: ${URL_PREFIX}
        PORT: ${PORT}
    networks:
      backend_bridge:
        ipv4_address: 10.0.0.5

  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:80
    environment:
      - PORT=${PORT}
    networks:
      backend_bridge:
        ipv4_address: 10.0.0.6

networks:
  backend_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/18
