# Generated by Django 3.1 on 2022-04-04 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_muscle_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RememberMe',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.musclegroup'),
        ),
    ]
