name: CI

# Triggers workflow on pushes to main.
on:
  push:
    branches:
      - main

jobs:
  # Uses Heroku secrets to log in and deploy the frontend and backend apps.
  deploy:
    name: Deploy frontend & backend
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Dpl tool
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y ruby-dev
          sudo gem install dpl

      - name: Deploy to Heroku
        run: |
          sudo dpl --provider=heroku --app=ase-group4-secfit-frontend --api-key=$HEROKU_STAGING_API_KEY
          sudo dpl --provider=heroku --app=ase-group4-secfit-backend --api-key=$HEROKU_STAGING_API_KEY
        env:
          HEROKU_STAGING_API_KEY: ${{ secrets.HEROKU_STAGING_API_KEY }}
