name: Review Guidelines

on:
  pull_request:

jobs:
  checklist:
    name: Checklist
    runs-on: ubuntu-latest

    steps:
      - name: Post checklist
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            ### Code Review Checklist

            **General**
            - Is there logic in the frontend that should be moved to the backend, or vice versa?
            - Does the code pass the implemented automatic review tools?

            **For: classes, methods, functions, variables**
            - Is the purpose of the class/method/function/variable obvious from its name?

            **For: classes, methods, functions**
            - Does the class/method/function have low cohesion, and should be split up?
            - Are any of the classes/methods/functions tightly coupled, and should be combined?
            - Is the class/method/function self-explanatory, and if not, does it have an explanatory docstring?
            - Is there repeated code in any of the classes/methods/functions, that should be extracted into a parent class/helper function?
            - Is the class/method/function located where you expect to find it in the file hierarchy, and within the file?

            **For: classes**
            - Does every class have only a single responsibility?

            **For: methods, functions**
            - JavaScript: Does the method/function have JSDoc type annotations for its parameters and return value?

            **For: variables**
            - JavaScript: If the variable is not later redefined, is it declared as `const`?
